[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    Expires = "off"
    Pragma = "no-cache"
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    Expires = "off"
    Pragma = "no-cache"
